// <auto-generated />
using System;
using AuditorPRO.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuditorPRO.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260408184203_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuditorPRO.Domain.Entities.AsignacionRolUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("AsignadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExpedienteRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("FechaAsignacion")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaVencimiento")
                        .HasColumnType("date");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("AsignacionesRol");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.BitacoraEvento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Accion")
                        .HasColumnType("int");

                    b.Property<string>("DatosAntes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DatosDespues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorDetalle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Exitoso")
                        .HasColumnType("bit");

                    b.Property<string>("IpOrigen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OcurridoAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Recurso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecursoId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("OcurridoAt");

                    b.HasIndex("UsuarioId", "OcurridoAt");

                    b.ToTable("Bitacora");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.Conector", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AuthType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConfiguracionJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecretKeyVaultRef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sistema")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoConector")
                        .HasColumnType("int");

                    b.Property<int>("TotalEjecuciones")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UltimaEjecucion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("UltimaEjecucionExito")
                        .HasColumnType("bit");

                    b.Property<string>("UltimoError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UrlEndpoint")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Conectores");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.ConflictoSoD", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MitigacionDoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Riesgo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RolAId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RolBId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Sistema")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RolAId");

                    b.HasIndex("RolBId");

                    b.ToTable("ConflictosSoD");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SociedadId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SociedadId");

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.DominioAuditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dominios");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.EmpleadoMaestro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CorreoCorporativo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<string>("EntraIdObject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoLaboral")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("FechaBaja")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaIngreso")
                        .HasColumnType("date");

                    b.Property<string>("FuenteOrigen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("JefeEmpleadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LoteCargaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroEmpleado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("PuestoId")
                        .HasColumnType("int");

                    b.Property<int?>("SociedadId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("JefeEmpleadoId");

                    b.HasIndex("NumeroEmpleado")
                        .IsUnique();

                    b.HasIndex("PuestoId");

                    b.HasIndex("SociedadId");

                    b.HasIndex("EstadoLaboral", "SociedadId");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.Evidencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlobContainer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BlobUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescripcionArchivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("HallazgoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HashSha256")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SimulacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SubidoAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubidoPor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TamanoBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("TipoEvidencia")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Verificada")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("HallazgoId");

                    b.ToTable("Evidencias");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.Hallazgo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnalisisIa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Criticidad")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("EvidenciaCierreIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("FechaCierre")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaCompromiso")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NormaAfectada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanAccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsableEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ResultadoControlId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RiesgoAsociado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SimulacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("SociedadId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ResultadoControlId");

                    b.HasIndex("SimulacionId");

                    b.HasIndex("SociedadId");

                    b.ToTable("Hallazgos");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.LogConector", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConectorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DuracionMs")
                        .HasColumnType("int");

                    b.Property<DateTime>("EjecutadoAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EjecutadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Exitoso")
                        .HasColumnType("bit");

                    b.Property<string>("MensajeError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RegistrosProcesados")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConectorId");

                    b.ToTable("LogsConector");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.MatrizPuestoRol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Justificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PuestoId")
                        .HasColumnType("int");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tipo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("VigenteDesdE")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("PuestoId");

                    b.HasIndex("RolId");

                    b.ToTable("MatrizPuestoRol");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.Politica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contenido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("FechaRevision")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaVigencia")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NormaReferencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Responsable")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Politicas");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.Puesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NivelRiesgo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SociedadId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SociedadId");

                    b.ToTable("Puestos");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.PuntoControl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CondicionAmarillo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CondicionRojo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CondicionVerde")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CriticidadBase")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DominioId")
                        .HasColumnType("int");

                    b.Property<string>("EvidenciaRequerida")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormaReferencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuerySql")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoEvaluacion")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VersionRegla")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DominioId");

                    b.ToTable("PuntosControl");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.ResultadoControl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnalisisIa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Criticidad")
                        .HasColumnType("int");

                    b.Property<string>("DatosEvaluados")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EvaluadoAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EvidenciaEncontrada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EvidenciaFaltante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("FechaCompromisoSug")
                        .HasColumnType("date");

                    b.Property<int>("PuntoControlId")
                        .HasColumnType("int");

                    b.Property<string>("Recomendacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsableSugerido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultadoDetalle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Semaforo")
                        .HasColumnType("int");

                    b.Property<Guid>("SimulacionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("SociedadId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PuntoControlId");

                    b.HasIndex("SociedadId");

                    b.HasIndex("SimulacionId", "Semaforo");

                    b.ToTable("ResultadosControl");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.RolSistema", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsCritico")
                        .HasColumnType("bit");

                    b.Property<string>("NivelRiesgo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sistema")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RolesSistema");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.SimulacionAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletadaAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ControlesAmarillo")
                        .HasColumnType("int");

                    b.Property<int?>("ControlesRojo")
                        .HasColumnType("int");

                    b.Property<int?>("ControlesVerde")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DominioIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DuracionSegundos")
                        .HasColumnType("int");

                    b.Property<string>("ErrorDetalle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("IniciadaAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IniciadaPor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Periodicidad")
                        .HasColumnType("int");

                    b.Property<DateOnly>("PeriodoFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PeriodoInicio")
                        .HasColumnType("date");

                    b.Property<decimal?>("PorcentajeCumplimiento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PuntosControlIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ScoreMadurez")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SociedadIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<int?>("TotalControles")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Estado", "IniciadaAt");

                    b.ToTable("Simulaciones");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.Sociedad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Pais")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Sociedades");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.UsuarioSistema", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("EmpleadoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaUltimoAcceso")
                        .HasColumnType("datetime2");

                    b.Property<string>("FuenteOrigen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sistema")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("UsuariosSistema");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.AsignacionRolUsuario", b =>
                {
                    b.HasOne("AuditorPRO.Domain.Entities.RolSistema", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuditorPRO.Domain.Entities.UsuarioSistema", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.ConflictoSoD", b =>
                {
                    b.HasOne("AuditorPRO.Domain.Entities.RolSistema", "RolA")
                        .WithMany()
                        .HasForeignKey("RolAId");

                    b.HasOne("AuditorPRO.Domain.Entities.RolSistema", "RolB")
                        .WithMany()
                        .HasForeignKey("RolBId");

                    b.Navigation("RolA");

                    b.Navigation("RolB");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.Departamento", b =>
                {
                    b.HasOne("AuditorPRO.Domain.Entities.Sociedad", "Sociedad")
                        .WithMany("Departamentos")
                        .HasForeignKey("SociedadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sociedad");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.EmpleadoMaestro", b =>
                {
                    b.HasOne("AuditorPRO.Domain.Entities.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("DepartamentoId");

                    b.HasOne("AuditorPRO.Domain.Entities.EmpleadoMaestro", "JefeEmpleado")
                        .WithMany()
                        .HasForeignKey("JefeEmpleadoId");

                    b.HasOne("AuditorPRO.Domain.Entities.Puesto", "Puesto")
                        .WithMany()
                        .HasForeignKey("PuestoId");

                    b.HasOne("AuditorPRO.Domain.Entities.Sociedad", "Sociedad")
                        .WithMany("Empleados")
                        .HasForeignKey("SociedadId");

                    b.Navigation("Departamento");

                    b.Navigation("JefeEmpleado");

                    b.Navigation("Puesto");

                    b.Navigation("Sociedad");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.Evidencia", b =>
                {
                    b.HasOne("AuditorPRO.Domain.Entities.Hallazgo", "Hallazgo")
                        .WithMany("Evidencias")
                        .HasForeignKey("HallazgoId");

                    b.Navigation("Hallazgo");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.Hallazgo", b =>
                {
                    b.HasOne("AuditorPRO.Domain.Entities.ResultadoControl", "ResultadoControl")
                        .WithMany()
                        .HasForeignKey("ResultadoControlId");

                    b.HasOne("AuditorPRO.Domain.Entities.SimulacionAuditoria", "Simulacion")
                        .WithMany()
                        .HasForeignKey("SimulacionId");

                    b.HasOne("AuditorPRO.Domain.Entities.Sociedad", "Sociedad")
                        .WithMany()
                        .HasForeignKey("SociedadId");

                    b.Navigation("ResultadoControl");

                    b.Navigation("Simulacion");

                    b.Navigation("Sociedad");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.LogConector", b =>
                {
                    b.HasOne("AuditorPRO.Domain.Entities.Conector", "Conector")
                        .WithMany("Logs")
                        .HasForeignKey("ConectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conector");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.MatrizPuestoRol", b =>
                {
                    b.HasOne("AuditorPRO.Domain.Entities.Puesto", "Puesto")
                        .WithMany()
                        .HasForeignKey("PuestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuditorPRO.Domain.Entities.RolSistema", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Puesto");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.Puesto", b =>
                {
                    b.HasOne("AuditorPRO.Domain.Entities.Sociedad", "Sociedad")
                        .WithMany("Puestos")
                        .HasForeignKey("SociedadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sociedad");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.PuntoControl", b =>
                {
                    b.HasOne("AuditorPRO.Domain.Entities.DominioAuditoria", "Dominio")
                        .WithMany("PuntosControl")
                        .HasForeignKey("DominioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dominio");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.ResultadoControl", b =>
                {
                    b.HasOne("AuditorPRO.Domain.Entities.PuntoControl", "PuntoControl")
                        .WithMany()
                        .HasForeignKey("PuntoControlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuditorPRO.Domain.Entities.SimulacionAuditoria", "Simulacion")
                        .WithMany("Resultados")
                        .HasForeignKey("SimulacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuditorPRO.Domain.Entities.Sociedad", "Sociedad")
                        .WithMany()
                        .HasForeignKey("SociedadId");

                    b.Navigation("PuntoControl");

                    b.Navigation("Simulacion");

                    b.Navigation("Sociedad");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.UsuarioSistema", b =>
                {
                    b.HasOne("AuditorPRO.Domain.Entities.EmpleadoMaestro", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.Conector", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.DominioAuditoria", b =>
                {
                    b.Navigation("PuntosControl");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.Hallazgo", b =>
                {
                    b.Navigation("Evidencias");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.SimulacionAuditoria", b =>
                {
                    b.Navigation("Resultados");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.Sociedad", b =>
                {
                    b.Navigation("Departamentos");

                    b.Navigation("Empleados");

                    b.Navigation("Puestos");
                });
#pragma warning restore 612, 618
        }
    }
}
