// <auto-generated />
using System;
using AuditorPRO.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuditorPRO.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260414035621_v3_LoteCarga")]
    partial class v3_LoteCarga
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("AuditorPRO.Domain.Entities.AsignacionRolUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AsignadoPor")
                        .HasColumnType("TEXT");

                    b.Property<string>("CasoSESuiteRef")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpedienteRef")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("FechaAsignacion")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("FechaVencimiento")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RolId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("AsignacionesRol");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.BaseConocimiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ControlesDetectados")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreadoAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DominioDetectado")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorDetalle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FuenteIngesta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IngresadoPor")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RutaOriginal")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT");

                    b.Property<long>("TamanoBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TextoCompleto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoArchivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalPaginas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalPalabras")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BaseConocimiento");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.BitacoraEvento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Accion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DatosAntes")
                        .HasColumnType("TEXT");

                    b.Property<string>("DatosDespues")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorDetalle")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Exitoso")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IpOrigen")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OcurridoAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Recurso")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecursoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OcurridoAt");

                    b.HasIndex("UsuarioId", "OcurridoAt");

                    b.ToTable("Bitacora");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.CasoSESuite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Aprobador")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArchivoAdjuntoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cedula")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("EstadoCaso")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("FechaAprobacion")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("FechaVencimiento")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("LoteCargaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroCaso")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RolJustificado")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .HasColumnType("TEXT");

                    b.Property<string>("TransaccionesJustificadas")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioSAP")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NumeroCaso")
                        .IsUnique();

                    b.HasIndex("UsuarioSAP", "RolJustificado");

                    b.ToTable("CasosSESuite");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.Conector", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfiguracionJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SecretKeyVaultRef")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sistema")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoConector")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalEjecuciones")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UltimaEjecucion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UltimaEjecucionExito")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UltimoError")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlEndpoint")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Conectores");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.ConflictoSoD", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("MitigacionDoc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Riesgo")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RolAId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RolBId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sistema")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RolAId");

                    b.HasIndex("RolBId");

                    b.ToTable("ConflictosSoD");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SociedadId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SociedadId");

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.DominioAuditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Dominios");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.EmpleadoMaestro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cedula")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorreoCorporativo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DepartamentoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntraIdObject")
                        .HasColumnType("TEXT");

                    b.Property<int>("EstadoLaboral")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("FechaBaja")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("FechaIngreso")
                        .HasColumnType("TEXT");

                    b.Property<string>("FuenteOrigen")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("JefeEmpleadoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LoteCargaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroEmpleado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PuestoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SociedadId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("JefeEmpleadoId");

                    b.HasIndex("NumeroEmpleado")
                        .IsUnique();

                    b.HasIndex("PuestoId");

                    b.HasIndex("SociedadId");

                    b.HasIndex("EstadoLaboral", "SociedadId");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.Evidencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BlobContainer")
                        .HasColumnType("TEXT");

                    b.Property<string>("BlobUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescripcionArchivo")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("HallazgoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("HashSha256")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SimulacionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubidoAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubidoPor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("TamanoBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoEvidencia")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Verificada")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HallazgoId");

                    b.ToTable("Evidencias");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.FuenteDatoSimulacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LoteCargaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SimulacionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoFuente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalRegistros")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SimulacionId");

                    b.ToTable("FuentesDatosSimulacion");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.Hallazgo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnalisisIa")
                        .HasColumnType("TEXT");

                    b.Property<string>("CasoSESuiteRef")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cedula")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("Criticidad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EvidenciaCierreIds")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EvidenciaGenerada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateOnly?>("FechaCierre")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("FechaCompromiso")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormaAfectada")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanAccion")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponsableEmail")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ResultadoControlId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RiesgoAsociado")
                        .HasColumnType("TEXT");

                    b.Property<string>("RolAfectado")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SimulacionId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SociedadId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoHallazgo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TransaccionesAfectadas")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioSAP")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ResultadoControlId");

                    b.HasIndex("SimulacionId");

                    b.HasIndex("SociedadId");

                    b.ToTable("Hallazgos");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.LogConector", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ConectorId")
                        .HasColumnType("TEXT");

                    b.Property<int>("DuracionMs")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EjecutadoAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EjecutadoPor")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Exitoso")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MensajeError")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RegistrosProcesados")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConectorId");

                    b.ToTable("LogsConector");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.LoteCarga", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Actualizados")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CargadoPor")
                        .HasColumnType("TEXT");

                    b.Property<int>("Errores")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EsVigente")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("TEXT");

                    b.Property<int>("Insertados")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreArchivo")
                        .HasColumnType("TEXT");

                    b.Property<string>("SociedadCodigo")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("SociedadNombre")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoCarga")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalRegistros")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TipoCarga", "EsVigente");

                    b.HasIndex("TipoCarga", "SociedadCodigo", "FechaCarga");

                    b.ToTable("LotesCarga");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.MatrizPuestoRol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Justificacion")
                        .HasColumnType("TEXT");

                    b.Property<int>("PuestoId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RolId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("VigenteDesdE")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PuestoId");

                    b.HasIndex("RolId");

                    b.ToTable("MatrizPuestoRol");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.MatrizPuestoSAP", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cedula")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Departamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("FechaRevisionContraloria")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("FinValidez")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("InicioValidez")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("LoteCargaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCompleto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Puesto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sociedad")
                        .HasColumnType("TEXT");

                    b.Property<string>("Transaccion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UltimoIngreso")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioSAP")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Cedula");

                    b.HasIndex("Puesto", "Rol");

                    b.ToTable("MatrizPuestosSAP");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.Politica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Contenido")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentoUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("FechaRevision")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("FechaVigencia")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormaReferencia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Responsable")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Politicas");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.Puesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NivelRiesgo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SociedadId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SociedadId");

                    b.ToTable("Puestos");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.PuntoControl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CondicionAmarillo")
                        .HasColumnType("TEXT");

                    b.Property<string>("CondicionRojo")
                        .HasColumnType("TEXT");

                    b.Property<string>("CondicionVerde")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CriticidadBase")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<int>("DominioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EvidenciaRequerida")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormaReferencia")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuerySql")
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoEvaluacion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionRegla")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DominioId");

                    b.ToTable("PuntosControl");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.RegistroEntraID", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AccountEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobTitle")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSignInDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Manager")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OfficeLocation")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserPrincipalName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("SnapshotId", "EmployeeId");

                    b.ToTable("RegistrosEntraID");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.ResultadoControl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AnalisisIa")
                        .HasColumnType("TEXT");

                    b.Property<int>("Criticidad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DatosEvaluados")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EvaluadoAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenciaEncontrada")
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenciaFaltante")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("FechaCompromisoSug")
                        .HasColumnType("TEXT");

                    b.Property<int>("PuntoControlId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Recomendacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponsableSugerido")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultadoDetalle")
                        .HasColumnType("TEXT");

                    b.Property<int>("Semaforo")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SimulacionId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SociedadId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PuntoControlId");

                    b.HasIndex("SociedadId");

                    b.HasIndex("SimulacionId", "Semaforo");

                    b.ToTable("ResultadosControl");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.RolSistema", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsCritico")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NivelRiesgo")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sistema")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TransaccionesAutorizadas")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RolesSistema");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.SimulacionAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletadaAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ControlesAmarillo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ControlesRojo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ControlesVerde")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("DominioIds")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DuracionSegundos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorDetalle")
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FechaReferenciaDatos")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IniciadaAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IniciadaPor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LotesUsadosJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Objetivo")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Periodicidad")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("PeriodoFin")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("PeriodoInicio")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PorcentajeCumplimiento")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("PuntosControlIds")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResumenResultados")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ScoreMadurez")
                        .HasPrecision(4, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("SociedadIds")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoSimulacion")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TotalControles")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalCriticos")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Estado", "IniciadaAt");

                    b.ToTable("Simulaciones");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.SnapshotEntraID", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreadoPor")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInstantanea")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalRegistros")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FechaInstantanea");

                    b.ToTable("SnapshotsEntraID");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.Sociedad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pais")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Sociedades");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.UsuarioSistema", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cedula")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Departamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("EmpleadoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FechaUltimoAcceso")
                        .HasColumnType("TEXT");

                    b.Property<string>("FuenteOrigen")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NombreCompleto")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Puesto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sistema")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sociedad")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoUsuario")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("Sistema", "Cedula");

                    b.HasIndex("Sistema", "NombreUsuario");

                    b.ToTable("UsuariosSistema");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.AsignacionRolUsuario", b =>
                {
                    b.HasOne("AuditorPRO.Domain.Entities.RolSistema", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuditorPRO.Domain.Entities.UsuarioSistema", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.ConflictoSoD", b =>
                {
                    b.HasOne("AuditorPRO.Domain.Entities.RolSistema", "RolA")
                        .WithMany()
                        .HasForeignKey("RolAId");

                    b.HasOne("AuditorPRO.Domain.Entities.RolSistema", "RolB")
                        .WithMany()
                        .HasForeignKey("RolBId");

                    b.Navigation("RolA");

                    b.Navigation("RolB");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.Departamento", b =>
                {
                    b.HasOne("AuditorPRO.Domain.Entities.Sociedad", "Sociedad")
                        .WithMany("Departamentos")
                        .HasForeignKey("SociedadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sociedad");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.EmpleadoMaestro", b =>
                {
                    b.HasOne("AuditorPRO.Domain.Entities.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("DepartamentoId");

                    b.HasOne("AuditorPRO.Domain.Entities.EmpleadoMaestro", "JefeEmpleado")
                        .WithMany()
                        .HasForeignKey("JefeEmpleadoId");

                    b.HasOne("AuditorPRO.Domain.Entities.Puesto", "Puesto")
                        .WithMany()
                        .HasForeignKey("PuestoId");

                    b.HasOne("AuditorPRO.Domain.Entities.Sociedad", "Sociedad")
                        .WithMany("Empleados")
                        .HasForeignKey("SociedadId");

                    b.Navigation("Departamento");

                    b.Navigation("JefeEmpleado");

                    b.Navigation("Puesto");

                    b.Navigation("Sociedad");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.Evidencia", b =>
                {
                    b.HasOne("AuditorPRO.Domain.Entities.Hallazgo", "Hallazgo")
                        .WithMany("Evidencias")
                        .HasForeignKey("HallazgoId");

                    b.Navigation("Hallazgo");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.FuenteDatoSimulacion", b =>
                {
                    b.HasOne("AuditorPRO.Domain.Entities.SimulacionAuditoria", null)
                        .WithMany("FuentesDatos")
                        .HasForeignKey("SimulacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.Hallazgo", b =>
                {
                    b.HasOne("AuditorPRO.Domain.Entities.ResultadoControl", "ResultadoControl")
                        .WithMany()
                        .HasForeignKey("ResultadoControlId");

                    b.HasOne("AuditorPRO.Domain.Entities.SimulacionAuditoria", "Simulacion")
                        .WithMany()
                        .HasForeignKey("SimulacionId");

                    b.HasOne("AuditorPRO.Domain.Entities.Sociedad", "Sociedad")
                        .WithMany()
                        .HasForeignKey("SociedadId");

                    b.Navigation("ResultadoControl");

                    b.Navigation("Simulacion");

                    b.Navigation("Sociedad");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.LogConector", b =>
                {
                    b.HasOne("AuditorPRO.Domain.Entities.Conector", "Conector")
                        .WithMany("Logs")
                        .HasForeignKey("ConectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conector");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.MatrizPuestoRol", b =>
                {
                    b.HasOne("AuditorPRO.Domain.Entities.Puesto", "Puesto")
                        .WithMany()
                        .HasForeignKey("PuestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuditorPRO.Domain.Entities.RolSistema", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Puesto");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.Puesto", b =>
                {
                    b.HasOne("AuditorPRO.Domain.Entities.Sociedad", "Sociedad")
                        .WithMany("Puestos")
                        .HasForeignKey("SociedadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sociedad");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.PuntoControl", b =>
                {
                    b.HasOne("AuditorPRO.Domain.Entities.DominioAuditoria", "Dominio")
                        .WithMany("PuntosControl")
                        .HasForeignKey("DominioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dominio");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.RegistroEntraID", b =>
                {
                    b.HasOne("AuditorPRO.Domain.Entities.SnapshotEntraID", "Snapshot")
                        .WithMany("Registros")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.ResultadoControl", b =>
                {
                    b.HasOne("AuditorPRO.Domain.Entities.PuntoControl", "PuntoControl")
                        .WithMany()
                        .HasForeignKey("PuntoControlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuditorPRO.Domain.Entities.SimulacionAuditoria", "Simulacion")
                        .WithMany("Resultados")
                        .HasForeignKey("SimulacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuditorPRO.Domain.Entities.Sociedad", "Sociedad")
                        .WithMany()
                        .HasForeignKey("SociedadId");

                    b.Navigation("PuntoControl");

                    b.Navigation("Simulacion");

                    b.Navigation("Sociedad");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.UsuarioSistema", b =>
                {
                    b.HasOne("AuditorPRO.Domain.Entities.EmpleadoMaestro", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.Conector", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.DominioAuditoria", b =>
                {
                    b.Navigation("PuntosControl");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.Hallazgo", b =>
                {
                    b.Navigation("Evidencias");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.SimulacionAuditoria", b =>
                {
                    b.Navigation("FuentesDatos");

                    b.Navigation("Resultados");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.SnapshotEntraID", b =>
                {
                    b.Navigation("Registros");
                });

            modelBuilder.Entity("AuditorPRO.Domain.Entities.Sociedad", b =>
                {
                    b.Navigation("Departamentos");

                    b.Navigation("Empleados");

                    b.Navigation("Puestos");
                });
#pragma warning restore 612, 618
        }
    }
}
